extends: airbnb-base
env:
  node: true
rules:
  no-param-reassign: 0
  arrow-body-style: 0
  no-console: 0
  class-methods-use-this: 0
  import/no-dynamic-require: 0
  global-require: 0
  comma-dangle: 0
  import/no-unresolved: 0
